// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ClientApp.GetAJob.WebService {
    
    
    /// <remarks/>
    /// <remarks>
///Get A Job WebService
///</remarks>
    [System.Web.Services.WebServiceBinding(Name="ServiceSoap", Namespace="http://www.getajob.org/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOffersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPeopleOperationCompleted;
        
        public Service() {
            this.Url = "http://localhost:8080/Service.asmx";
        }
        
        public Service(string url) {
            this.Url = url;
        }
        
        public event getOffersCompletedEventHandler getOffersCompleted;
        
        public event getPeopleCompletedEventHandler getPeopleCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.getajob.org/getOffers", RequestNamespace="http://www.getajob.org/", ResponseNamespace="http://www.getajob.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public JobOffer[] getOffers(int page_index, int per_page) {
            object[] results = this.Invoke("getOffers", new object[] {
                        page_index,
                        per_page});
            return ((JobOffer[])(results[0]));
        }
        
        public System.IAsyncResult BegingetOffers(int page_index, int per_page, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getOffers", new object[] {
                        page_index,
                        per_page}, callback, asyncState);
        }
        
        public JobOffer[] EndgetOffers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((JobOffer[])(results[0]));
        }
        
        public void getOffersAsync(int page_index, int per_page) {
            this.getOffersAsync(page_index, per_page, null);
        }
        
        public void getOffersAsync(int page_index, int per_page, object userState) {
            if ((this.getOffersOperationCompleted == null)) {
                this.getOffersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOffersCompleted);
            }
            this.InvokeAsync("getOffers", new object[] {
                        page_index,
                        per_page}, this.getOffersOperationCompleted, userState);
        }
        
        private void OngetOffersCompleted(object arg) {
            if ((this.getOffersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOffersCompleted(this, new getOffersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.getajob.org/getPeople", RequestNamespace="http://www.getajob.org/", ResponseNamespace="http://www.getajob.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Person[] getPeople(int page_index, int per_page) {
            object[] results = this.Invoke("getPeople", new object[] {
                        page_index,
                        per_page});
            return ((Person[])(results[0]));
        }
        
        public System.IAsyncResult BegingetPeople(int page_index, int per_page, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPeople", new object[] {
                        page_index,
                        per_page}, callback, asyncState);
        }
        
        public Person[] EndgetPeople(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Person[])(results[0]));
        }
        
        public void getPeopleAsync(int page_index, int per_page) {
            this.getPeopleAsync(page_index, per_page, null);
        }
        
        public void getPeopleAsync(int page_index, int per_page, object userState) {
            if ((this.getPeopleOperationCompleted == null)) {
                this.getPeopleOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPeopleCompleted);
            }
            this.InvokeAsync("getPeople", new object[] {
                        page_index,
                        per_page}, this.getPeopleOperationCompleted, userState);
        }
        
        private void OngetPeopleCompleted(object arg) {
            if ((this.getPeopleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPeopleCompleted(this, new getPeopleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.getajob.org/")]
    public partial class JobOffer : EntityBase {
        
        /// <remarks/>
        public string Company;
        
        /// <remarks/>
        public string JobDescription;
        
        /// <remarks/>
        public string Contact;
        
        /// <remarks/>
        public string JobTitle;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.getajob.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JobOffer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resume))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Person))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    public partial class EntityBase {
        
        /// <remarks/>
        public int Id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.getajob.org/")]
    public partial class Resume : EntityBase {
        
        /// <remarks/>
        public string LastEmployer;
        
        /// <remarks/>
        public string Content;
        
        /// <remarks/>
        public Person Person;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.getajob.org/")]
    public partial class Person : EntityBase {
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public string LastName;
        
        /// <remarks/>
        public Resume Resume;
        
        /// <remarks/>
        public User User;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.getajob.org/")]
    public partial class User : EntityBase {
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public string Email;
        
        /// <remarks/>
        public string PasswordHash;
        
        /// <remarks/>
        public string Salt;
        
        /// <remarks/>
        public Person Person;
    }
    
    public partial class getOffersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOffersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public JobOffer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JobOffer[])(this.results[0]));
            }
        }
    }
    
    public delegate void getOffersCompletedEventHandler(object sender, getOffersCompletedEventArgs args);
    
    public partial class getPeopleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPeopleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Person[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Person[])(this.results[0]));
            }
        }
    }
    
    public delegate void getPeopleCompletedEventHandler(object sender, getPeopleCompletedEventArgs args);
}
